extends: existence
message: "Don't use gerunds in headings. - %s"
link: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
nonword: true
level: warning
#scope: heading
type: context_find
context: '^ {0,2}#{1,6}.+'
action:
  name: edit
  params:
    - remove
    - '.?!'
tokens:
  - '\b\w*ing\b'

