extends: substitution
message: "Use '%s' instead of '%s'."
link: https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions
level: error
type: find_replace
ignorecase: true
action:
  name: replace
swap:
  '(\b[Oo]ne\b)(?! of:)': 1
  ' [Tt]wo\b': 2
  ' [Tt]hree\b': 3
  ' [Ff]our\b': 4
  ' [Ff]ive\b': 5
  ' [Ss]ix\b': 6
  ' [Ss]even\b': 7
  ' [Ee]ight\b': 8
  ' [Nn]ine\b': 9
  e\.g\.: for example
  E\.g\.: For example
  i\.e\.: that is
  roundtrip: round trip
  non functional: non-functional
  web sites: websites
exceptions:
  - 'One of\:'