extends: substitution
message: "Use '%s' instead of '%s'."
link: https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions
level: suggestion
type: find_replace
ignorecase: true
action:
  name: replace
swap:
  \b[Aa]re not\b: aren't
  \bcannot\b: can't
  \bcould not\b: couldn't
  \bdid not\b: didn't
  \bdo not\b: don't
  \bdoes not\b: doesn't
  \bhas not\b: hasn't
  \bhave not\b: haven't
  \bhow is\b: how's
  \bis not\b: isn't
  \bit is\b: it's
  \bshould not\b: shouldn't
  \bthat is\b: that's
  \bthey are\b: they're
  \bwas not\b: wasn't
  \bwe are\b: we're
  \bwe have\b: we've
  \bwere not\b: weren't
  \bwhat is\b: what's
  \bwhen is\b: when's
  \bwhere is\b: where's
  \bwill not\b: won't
