extends: substitution
message: "Use '%s' instead of '%s'."
link: https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions
level: error
type: find_replace
ignorecase: true
action:
  name: replace
swap:
  are not: aren't
  cannot: can't
  could not: couldn't
  did not: didn't
  do not: don't
  does not: doesn't
  has not: hasn't
  have not: haven't
  how is: how's
  is not: isn't
  it is: it's
  should not: shouldn't
  that is: that's
  they are: they're
  was not: wasn't
  we are: we're
  we have: we've
  were not: weren't
  what is: what's
  when is: when's
  where is: where's
  will not: won't
  e\.g\.: for example
  E\.g\.: For example
  i\.e\.: that is
  roundtrip: round trip
  non functional: non-functional
  web sites: websites
  ' [Oo]ne ': 1
  ' [Tt]wo ': 2
  ' [Tt]hree ': 3
  ' [Ff]our ': 4
  ' [Ff]ive ': 5
  ' [Ss]ix ': 6
  ' [Ss]even ': 7
  ' [Ee]ight ': 8
  ' [Nn]ine ': 9