extends: existence
message: "Dont do this stuff: '%s'"
link: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
level: error
scope: all
type: find
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
tokens:
  - Double punctuation: '[.?!,]{2,}[ \n]'
  - Don't start a sentence with a lower case lettre: '\. [a-z]{1,}'
  - Space comma space:  ' , ' 
  - Space then period: ' \.'
  - Double spaces: '[^\n] {2,}[^\.*-+\/]'
  - Double capitals at the start of a sentence:  ' [A-Z]{2}[a-z]+'
  - Passive voice: '[Ii]t is recommended'
exceptions:
  - '\ {2,}-'
  - ^ {2,}.*
  - '^ ?\* {2,}\.?'  
  - '.  \n'               #force new line in MD
  - '\/ {2,}'
