extends: existence
message: "Dont do this stuff: '%s'"
link: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
level: error
scope: all
type: find
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
tokens:
  - double punctuation: '[.?!,]{2,}[ \n]'
  - don't start a sentence with a lower case: '\. [a-z]{1,}'
  - 'space comma space':  ' , ' 
  - 'space then period': ' \.'
  - 'double spaces': '[^\n] {2,}[^\.*-+\/]'
  - 'Double capitals at the start of a sentence':  ' [A-Z]{2}[a-z]+'
exceptions:
  - '\ {2,}.'
  - ^ {2,}.*
  - '^ ?\* {2,}\.?'  
  - '.  \n'               #force new line in MD
