extends: existence
message: "Dont do this stuff: '%s'"
link: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
level: error
scope: all
type: find
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
tokens:
  - Double punctuation: '[.?!,]{2,}'
  - Don't start a sentence with a lower case lettre: '\. [a-z]{1,}'
  - Space comma space:  ' , ' 
  - Space then period: ' \.'
  - NDouble spaces: '\b\,?  \b'
  - Double capitals at the start of a sentence:  '\. [A-Z]{2}[a-z]+'
exceptions:
  - '\ {2,}[-\+]'
  - '^ {2,}\*'
  - '^ ?\* {2,}\.?'       #beginning of a line in jsdocs
  - '.  \n'               #force new line in MD
