extends: existence
message: "Double word suspected"
link: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
level: warning
scope: heading
type: find
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
tokens:
  - (\b.+?\b\s)\1 
