extends: substitution
message: "Use '%s' instead of '%s'."
link: https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions
level: error
type: find_replace
ignorecase: true
action:
  name: replace
swap:
  'Default is': 'Defaults to:'
  'Default:': 'Defaults to:'
  'Default value': 'Defaults to:'
  '(event .*) fire.?\s': trigger 