extends: existence
message: "Don't use end punctuation in headings."
link: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
nonword: true
level: warning
scope: heading
type: find
#context: "^ {0,2}#{1,6} .+"
action:
  name: edit
  params:
    - remove
    - '.?!'
tokens:
  - '[a-zA-Z]([.?!])'