extends: Use approved terminology
message: "Use '%s' instead of '%s'."
link: https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions
level: error
type: find_replace
ignorecase: true
action:
  name: replace
swap:
  'server[- ]?side': backend
  'client[- ]?side': frontend
  'back[- ]end': backend
  'front[- ]end': frontend
 # 'third[- ]?party': 3rd-party
  third-party|third party|3rd party: 3rd-party
  '(\ba[\.]?m[\.]?\b)|(\bA\.M[\.]?\b)': AM
  '(\bp[\.]?m[\.]?\b)|(\bP\.M[\.]?\b)': PM
  '\bhe\b|\bshe\b': they
  '[\b ]api[\b ]': API

  
